### ISSUE TITLE
Running Theme causes Panic on zero Value

### ISSUE THREAD

**Issue by faithbible** [djuelg/Shapez-Theme#7]
Love the design of the theme.  I'm running localhost on a Mac.  When I cloned and tried to launch, I got the below error.  Other themes seem to work fine for me.  Any advice?

```
Started building site
panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
panic(0x75de20, 0xc820263300)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
text/template.errRecover(0xc8208fadd0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:139 +0x2f0
panic(0x75de20, 0xc820263300)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
text/template.errRecover(0xc8208f9778)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:139 +0x2f0
panic(0x75de20, 0xc820263300)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:1671 +0x7b
github.com/spf13/hugo/tpl.in(0x66d6e0, 0xc82090a3c8, 0x0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template_funcs.go:400 +0x596
reflect.Value.call(0x719040, 0xa00b90, 0x13, 0x86a4b0, 0x4, 0xc82090a390, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x719040, 0xa00b90, 0x13, 0xc82090a390, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
text/template.(*state).evalCall(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0x719040, 0xa00b90, 0x13, 0x154d380, 0xc8202cb950, 0xc8202a9220, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:641 +0xb39
text/template.(*state).evalFunction(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0xc8202cb980, 0x154d380, 0xc8202cb950, 0xc8200ac540, 0x3, 0x4, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:515 +0x336
text/template.(*state).evalCommand(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0xc8202cb950, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:412 +0x1e9
text/template.(*state).evalPipeline(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0xc8200ab400, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).evalArg(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0x15440a8, 0x6660a0, 0x154d040, 0xc8200ab400, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:710 +0x43e
text/template.(*state).evalCall(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0x718dc0, 0xa019c8, 0x13, 0x154d380, 0xc8202cb860, 0xc8202a9207, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:622 +0x875
text/template.(*state).evalFunction(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0xc8202cb890, 0x154d380, 0xc8202cb860, 0xc8200ac580, 0x3, 0x4, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:515 +0x336
text/template.(*state).evalCommand(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0xc8202cb860, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:412 +0x1e9
text/template.(*state).evalPipeline(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0xc8200ab360, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).walkIfOrWith(0xc8208f9708, 0xa, 0x860280, 0xc8204bf400, 0x16, 0xc8200ab360, 0xc8202cba70, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:244 +0xb5
text/template.(*state).walk(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0x154d160, 0xc8200ac5c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:220 +0x4d9
text/template.(*state).walk(0xc8208f9708, 0x860280, 0xc8204bf400, 0x16, 0x1583420, 0xc8202cb080)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*Template).Execute(0xc8200ac240, 0x154a490, 0xc8201bbd50, 0x860280, 0xc8204bf400, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:178 +0x2a7
html/template.(*Template).Execute(0xc8202cb020, 0x154a490, 0xc8201bbd50, 0x860280, 0xc8204bf400, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:104 +0x9a
github.com/spf13/hugo/tpl.executeTemplate(0x860280, 0xc8204bf400, 0x154a490, 0xc8201bbd50, 0xc820273c40, 0x2, 0x2)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template.go:129 +0x196
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0x860280, 0xc8204bf400, 0xc820273c40, 0x2, 0x2, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template.go:146 +0xdf
github.com/spf13/hugo/tpl.partial(0xc82018eb72, 0xb, 0xc8208edc80, 0x1, 0x1, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template.go:115 +0x24e
reflect.Value.call(0x71ff80, 0xa00be8, 0x13, 0x86a4b0, 0x4, 0xc820900b70, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x71ff80, 0xa00be8, 0x13, 0xc820900b40, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
text/template.(*state).evalCall(0xc8208fad60, 0x860280, 0xc8202b6038, 0x196, 0x71ff80, 0xa00be8, 0x13, 0x154d380, 0xc8200b0780, 0xc82018eb69, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:641 +0xb39
text/template.(*state).evalFunction(0xc8208fad60, 0x860280, 0xc8202b6038, 0x196, 0xc8200b07b0, 0x154d380, 0xc8200b0780, 0xc8204cb080, 0x3, 0x4, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:515 +0x336
text/template.(*state).evalCommand(0xc8208fad60, 0x860280, 0xc8202b6038, 0x196, 0xc8200b0780, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:412 +0x1e9
text/template.(*state).evalPipeline(0xc8208fad60, 0x860280, 0xc8202b6038, 0x196, 0xc8201eac80, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).walk(0xc8208fad60, 0x860280, 0xc8202b6038, 0x196, 0x1548980, 0xc8200b0810)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:215 +0x135
text/template.(*state).walk(0xc8208fad60, 0x860280, 0xc8202b6038, 0x196, 0x1583420, 0xc82016bbf0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*state).walkRange.func1(0x668be0, 0xc8208ed720, 0x82, 0x860280, 0xc8202b6038, 0x196)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:310 +0x202
text/template.(*state).walkRange(0xc8208fad60, 0x82e000, 0xc82024ab40, 0x16, 0xc8204cb1c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:319 +0x465
text/template.(*state).walk(0xc8208fad60, 0x82e000, 0xc82024ab40, 0x16, 0x154d2c8, 0xc8204cb1c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:226 +0x264
text/template.(*state).walk(0xc8208fad60, 0x82e000, 0xc82024ab40, 0x16, 0x1583420, 0xc82016b6b0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*Template).Execute(0xc8204cab40, 0x154a490, 0xc8201c3340, 0x82e000, 0xc82024ab40, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:178 +0x2a7
html/template.(*Template).Execute(0xc82016b620, 0x154a490, 0xc8201c3340, 0x82e000, 0xc82024ab40, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:104 +0x9a
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc8204dc000, 0x82e000, 0xc82024ab40, 0xc8201d51e0, 0x18, 0x154a490, 0xc8201c3340, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:2044 +0xc2
github.com/spf13/hugo/hugolib.(*Site).render(0xc8204dc000, 0xc8208ecb70, 0xd, 0x82e000, 0xc82024ab40, 0x154a490, 0xc8201c3340, 0xc8208be400, 0x14, 0x20, ...)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:2018 +0x2be
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc8204dc000, 0xc8208ecb70, 0xd, 0xc820891438, 0x5, 0x82e000, 0xc82024ab40, 0xc8208be400, 0x14, 0x20, ...)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1938 +0x135
github.com/spf13/hugo/hugolib.(*Site).renderSectionLists(0xc8204dc000, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1655 +0x660
github.com/spf13/hugo/hugolib.(*Site).Render(0xc8204dc000, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:724 +0x104
github.com/spf13/hugo/hugolib.(*Site).Build(0xc8204dc000, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:380 +0x80
github.com/spf13/hugo/commands.buildSite(0xc8208fb867, 0x1, 0x1, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:688 +0x1b8
github.com/spf13/hugo/commands.build(0xc8208fb9ae, 0x1, 0x1, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:525 +0x3be
github.com/spf13/hugo/commands.server(0xc876e0, 0xc820257680, 0x0, 0x2, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/server.go:163 +0x6f2
github.com/spf13/cobra.(*Command).execute(0xc876e0, 0xc820257500, 0x2, 0x2, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/cobra/command.go:561 +0x62c
github.com/spf13/cobra.(*Command).ExecuteC(0xc860e0, 0xc876e0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/cobra/command.go:651 +0x55c
github.com/spf13/hugo/commands.Execute()
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:168 +0x77
main.main()
	/Users/spf13/gopath/src/github.com/spf13/hugo/main.go:26 +0x28
```

**Comment by djuelg** [comment]
Thanks :)
Uhm I think it's the same problem in issue #6 .
The theme seems to have problems with v0.16 and I didn't had the time to update it yet.

Unfortunately you can just wait some week,  go back to v0.15, search another theme or find the solution yourself...

Greets

**Comment by faithbible** [comment]
Thanks.  I had simply added `theme = "Shapez-Theme"` without checking the other parameters.  Stupid of me.
